apiVersion: config.projectsveltos.io/v1beta1
kind: ClusterProfile
metadata:
  name: ingress-nginx-prod-eu
spec:
  clusterRefs:
    - apiVersion: lib.projectsveltos.io/v1beta1
      kind: SveltosCluster
      namespace: projectsveltos
      name: prod-eu
  syncMode: ContinuousWithDriftDetection
  continueOnError: true
  patches:
    - target:
        annotationSelector: helm.sh/hook
      patch: |
        - op: add
          path: /metadata/annotations/projectsveltos.io~1driftDetectionIgnore
          value: ok
  policyRefs:
    - deploymentType: Remote
      remoteURL:
        url: oci://oci.hub.confighub.com/space/sveltos-ingress-nginx-prod-eu:latest
        interval: 1m0s
        secretRef:
          name: confighub-sveltos-targets
          namespace: projectsveltos
---
apiVersion: config.projectsveltos.io/v1beta1
kind: ClusterProfile
metadata:
  name: ingress-nginx-prod-us
spec:
  clusterRefs:
    - apiVersion: lib.projectsveltos.io/v1beta1
      kind: SveltosCluster
      namespace: projectsveltos
      name: prod-us
  syncMode: ContinuousWithDriftDetection
  continueOnError: true
  patches:
    - target:
        annotationSelector: helm.sh/hook
      patch: |
        - op: add
          path: /metadata/annotations/projectsveltos.io~1driftDetectionIgnore
          value: ok
  policyRefs:
    - deploymentType: Remote
      remoteURL:
        url: oci://oci.hub.confighub.com/space/sveltos-ingress-nginx-prod-us:latest
        interval: 1m0s
        secretRef:
          name: confighub-sveltos-targets
          namespace: projectsveltos
