apiVersion: config.projectsveltos.io/v1beta1
kind: ClusterProfile
metadata:
  name: ingress-nginx
spec:
  clusterSelector:
    matchLabels:
      env: prod
  syncMode: ContinuousWithDriftDetection
  helmCharts:
    - repositoryURL: https://kubernetes.github.io/ingress-nginx
      repositoryName: ingress-nginx
      chartName: ingress-nginx/ingress-nginx
      chartVersion: 4.15.1
      releaseName: ingress-nginx
      releaseNamespace: ingress-nginx
      helmChartAction: Install
---
apiVersion: config.projectsveltos.io/v1beta1
kind: ClusterProfile
metadata:
  name: kyverno
spec:
  clusterSelector:
    matchExpressions:
      - key: env
        operator: In
        values: [staging, prod]
  syncMode: ContinuousWithDriftDetection
  helmCharts:
    - repositoryURL: https://kyverno.github.io/kyverno/
      repositoryName: kyverno
      chartName: kyverno/kyverno
      chartVersion: 3.8.1
      releaseName: kyverno
      releaseNamespace: kyverno
      helmChartAction: Install
      values: |
        admissionController:
          replicas: 3
---
apiVersion: config.projectsveltos.io/v1beta1
kind: ClusterProfile
metadata:
  name: kyverno-policies
spec:
  clusterSelector:
    matchExpressions:
      - key: env
        operator: In
        values: [staging, prod]
  dependsOn: [kyverno]
  syncMode: ContinuousWithDriftDetection
  policyRefs:
    - kind: ConfigMap
      name: kyverno-policies
      namespace: default
