apiVersion: config.projectsveltos.io/v1beta1
kind: ClusterProfile
metadata:
  name: ingress-nginx-base
spec:
  clusterRefs: []
  syncMode: ContinuousWithDriftDetection
  helmCharts:
    - repositoryURL: https://kubernetes.github.io/ingress-nginx
      repositoryName: ingress-nginx
      chartName: ingress-nginx/ingress-nginx
      chartVersion: 4.15.1
      releaseName: ingress-nginx
      releaseNamespace: ingress-nginx
      helmChartAction: Install
