apiVersion: config.projectsveltos.io/v1beta1
kind: ClusterProfile
metadata:
  name: ingress-nginx-base
spec:
  clusterRefs: []
  helmCharts:
  - chartName: ingress-nginx/ingress-nginx
    chartVersion: 4.15.1
    helmChartAction: Install
    releaseName: ingress-nginx
    releaseNamespace: ingress-nginx
    repositoryName: ingress-nginx
    repositoryURL: https://kubernetes.github.io/ingress-nginx
  syncMode: ContinuousWithDriftDetection
